/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package actividad3;

import java.io.IOException;

/**
 *
 * @author crixo
 */
public class Formulario_frase extends javax.swing.JFrame {
    String archivo;
    /**
     * Creates new form Formulario_frase
     */
    public Formulario_frase(String autor, String frase, String archivoElegido) {
        initComponents();
        Lfrase.setText(frase);
        Lautor.setText(autor);
        archivo = archivoElegido;
        this.setVisible(true);
        setLocationRelativeTo(null);
        
        
    }
    
    
   
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Bvolver = new javax.swing.JButton();
        bsalir2 = new javax.swing.JButton();
        Botrafrease = new javax.swing.JButton();
        Lfrase = new javax.swing.JLabel();
        Lautor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(462, 259));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Bvolver.setText("Volver");
        Bvolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BvolverActionPerformed(evt);
            }
        });
        jPanel1.add(Bvolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 184, -1, -1));

        bsalir2.setText("Salir");
        bsalir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsalir2ActionPerformed(evt);
            }
        });
        jPanel1.add(bsalir2, new org.netbeans.lib.awtextra.AbsoluteConstraints(328, 184, -1, -1));

        Botrafrease.setText("Otra frase");
        Botrafrease.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotrafreaseActionPerformed(evt);
            }
        });
        jPanel1.add(Botrafrease, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 184, -1, -1));

        Lfrase.setFont(new java.awt.Font("Liberation Sans", 1, 10)); // NOI18N
        Lfrase.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(Lfrase, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 310, 110));

        Lautor.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(Lautor, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 150, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BvolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BvolverActionPerformed
        this.setVisible(false);
        new Formulario_principal().setVisible(true);
        
    }//GEN-LAST:event_BvolverActionPerformed

    private void bsalir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsalir2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_bsalir2ActionPerformed

    private void BotrafreaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotrafreaseActionPerformed
        String fraseElegida = Actividad3.elegirFrase(archivo);
        
    
    if (!fraseElegida.isEmpty()) {
        String[] partes = fraseElegida.split(" - ");
        
        if (partes.length == 2) {
            String frase = "<html>" + partes[0].replace("\n", "<br>") + "</html>";
            String autor = partes[1];
            
            Lfrase.setText(frase);
            Lautor.setText(autor);
        }
        }
    
    }//GEN-LAST:event_BotrafreaseActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Botrafrease;
    private javax.swing.JButton Bvolver;
    private javax.swing.JLabel Lautor;
    private javax.swing.JLabel Lfrase;
    private javax.swing.JButton bsalir2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
