/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package actividad4;

/**
 *
 * @author crixo
 */
public class Formulario_principal extends javax.swing.JFrame {

    /**
     * Creates new form Formulario_principal
     */
    public Formulario_principal() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bPeliculas = new javax.swing.JButton();
        bDirectores = new javax.swing.JButton();
        bActores = new javax.swing.JButton();
        bSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        bPeliculas.setForeground(new java.awt.Color(0, 0, 0));
        bPeliculas.setText("Peliculas");
        bPeliculas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bPeliculasActionPerformed(evt);
            }
        });

        bDirectores.setForeground(new java.awt.Color(0, 0, 0));
        bDirectores.setText("Directores");
        bDirectores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDirectoresActionPerformed(evt);
            }
        });

        bActores.setForeground(new java.awt.Color(0, 0, 0));
        bActores.setText("Actores");
        bActores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActoresActionPerformed(evt);
            }
        });

        bSalir.setForeground(new java.awt.Color(0, 0, 0));
        bSalir.setText("Salir");
        bSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(bPeliculas)
                .addGap(82, 82, 82)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bDirectores)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(bSalir)))
                .addGap(84, 84, Short.MAX_VALUE)
                .addComponent(bActores)
                .addGap(93, 93, 93))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bPeliculas)
                    .addComponent(bDirectores)
                    .addComponent(bActores))
                .addGap(72, 72, 72)
                .addComponent(bSalir)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bActoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActoresActionPerformed
        this.setVisible(false);
        Formulario_Actores actores = new Formulario_Actores();
        actores.setVisible(true);
        actores.setLocationRelativeTo(null);
    }//GEN-LAST:event_bActoresActionPerformed

    private void bPeliculasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bPeliculasActionPerformed
        this.setVisible(false);
        Formulario_Peliculas peliculas = new Formulario_Peliculas();
        peliculas.setVisible(true);
        peliculas.setLocationRelativeTo(null);
    }//GEN-LAST:event_bPeliculasActionPerformed

    private void bDirectoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDirectoresActionPerformed
        this.setVisible(false);
        Formulario_Directores directores = new Formulario_Directores();
        directores.setVisible(true);
        directores.setLocationRelativeTo(null);
    }//GEN-LAST:event_bDirectoresActionPerformed

    private void bSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_bSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bActores;
    private javax.swing.JButton bDirectores;
    private javax.swing.JButton bPeliculas;
    private javax.swing.JButton bSalir;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
